/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCoachingTopic' : ActorMethod<[string], undefined>,
  'addGoals' : ActorMethod<[string, Array<string>], undefined>,
  'addSessionToHistory' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAvailability' : ActorMethod<[], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoachingTopics' : ActorMethod<[], Array<string>>,
  'getGoals' : ActorMethod<[Principal, string], Array<string>>,
  'getSessionHistory' : ActorMethod<
    [Principal],
    { 'Empty' : boolean } |
      { 'Sessions' : Array<string> }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeGoal' : ActorMethod<
    [string, string],
    { 'Success' : string } |
      { 'Failure' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setGoals' : ActorMethod<[string, Array<string>], undefined>,
  'startSession' : ActorMethod<
    [string],
    { 'Error' : string } |
      { 'Success' : string }
  >,
  'toggleAvailability' : ActorMethod<[boolean], undefined>,
  'validateGoal' : ActorMethod<
    [Principal, string, string],
    { 'GoalNotFound' : string } |
      { 'GoalExists' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];