/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCoachingTopic' : IDL.Func([IDL.Text], [], []),
  'addGoals' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'addSessionToHistory' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAvailability' : IDL.Func([], [IDL.Bool], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoachingTopics' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getGoals' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getSessionHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'Empty' : IDL.Bool, 'Sessions' : IDL.Vec(IDL.Text) })],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeGoal' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'Success' : IDL.Text, 'Failure' : IDL.Text })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setGoals' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'startSession' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'Error' : IDL.Text, 'Success' : IDL.Text })],
      [],
    ),
  'toggleAvailability' : IDL.Func([IDL.Bool], [], []),
  'validateGoal' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text],
      [IDL.Variant({ 'GoalNotFound' : IDL.Text, 'GoalExists' : IDL.Text })],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCoachingTopic' : IDL.Func([IDL.Text], [], []),
    'addGoals' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'addSessionToHistory' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAvailability' : IDL.Func([], [IDL.Bool], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoachingTopics' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getGoals' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getSessionHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'Empty' : IDL.Bool, 'Sessions' : IDL.Vec(IDL.Text) })],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeGoal' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'Success' : IDL.Text, 'Failure' : IDL.Text })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setGoals' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'startSession' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Error' : IDL.Text, 'Success' : IDL.Text })],
        [],
      ),
    'toggleAvailability' : IDL.Func([IDL.Bool], [], []),
    'validateGoal' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text],
        [IDL.Variant({ 'GoalNotFound' : IDL.Text, 'GoalExists' : IDL.Text })],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };